### PR TITLE
Upgrade Checkstyle to 10.14.0

### PR DESCRIPTION
**Pull request by wborn**
Upgrades Checkstyle from 10.6.0 to 10.14.0.

For release notes, see:

https://checkstyle.sourceforge.io/releasenotes.html

### CODE REVIEW

**Review by holgerfriedrich — APPROVED** [review]
LGTM!

**Comment by holgerfriedrich** [comment]
I just did a comparison of 0.15.0 agains 0.16.0-SNAPSHOT (with #462 and #463) applied on openhab-core. I have removed the clutter by adding ```<suppress files=".+\.java" checks="TodoCommentCheck|NullAnnotationsCheck|MethodNameCheck|StaticVariableNameCheck|MemberNameCheck|LocalVariableNameCheck|PackageNameCheck|TypeNameCheck|ConstantNameCheck"/>``` in ```suppressions.xml```and got the following result:
grafik

PMD seems to give more results, but for the files I checked, this is fine.

**Comment by holgerfriedrich** [comment]
btw: Once we get #462 and #463, we should release.
The benefit it support for Java 21 (i.e. support for running SAT checks on class files generated with Java 21).

**Comment by wborn** [comment]
That looks good! :slightly_smiling_face: 
A new release would be nice as it will also fix lots of annoying warnings (https://github.com/openhab/static-code-analysis/pull/453).

**Comment by holgerfriedrich** [comment]
Hello @openhab/sat-maintainers , kindly asking to review/merge this PR. We need this as one of the last pieces towards a Java21 build. Thanks!

See comments above:
> btw: Once we get https://github.com/openhab/static-code-analysis/pull/462 and https://github.com/openhab/static-code-analysis/pull/463, we should release.
The benefit it support for Java 21 (i.e. support for running SAT checks on class files generated with Java 21).

**Review by kaikreuzer — APPROVED** [review]
Sure thing - thanks!

**Pull request merged**
