### PR TITLE
Removed checks related to MANIFEST.MF file

### PR DESCRIPTION
**Pull request by Hilbrand**
With the new build system this file is generated. So all checks become obsolete.

### CODE REVIEW

**Comment by wborn** [comment]
This seems to be related to the discussion in https://github.com/openhab/static-code-analysis/issues/341. We might still want to check for issues in manifests resulting from wrong parameters in bnd.bnd files, annotations or POM files. Because of there are so many ways that can influence the generated manifest, it may be easier to just check the generated manifest.

**Comment by kaikreuzer** [comment]
@Hilbrand: @wborn seems to have a point here, so shall we simply close this PR?

**Comment by Hilbrand** [comment]
In theory there might some value to it. But looking at these checks, most of these, if they would trigger, seems more of a problem in core than a user specific problem. So I'm not sure if it would be right to check in such a indirect way. I didn't see any concrete examples suggested of possible usefull checks. So I'm not sure what the actual validity is that it's useful to do the checks on the generated file.
I don't think the checks are currently run at all because the file location changed. So my guess is if we want to have useful checks we need to develop new checks or at least make sure the checks are run at all. Otherwise I think we should just remove them as it's just dead code.

**Comment by kaikreuzer** [comment]
@Hilbrand & @wborn What do you suggest on how to proceed here?

**Comment by Hilbrand** [comment]
This pr can be redone if needed. pr collects ~dust~ conflicts, so I'll close for now.

**Pull request closed without merging**
