### PR TITLE
Cleaned up pom structure

### PR DESCRIPTION
**Pull request by kaikreuzer**
Preparation for the 0.4.0 release

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, I just noticed that I missed updating the docs.
@svilenvul I did this PR since I do not think we can keep "org.openhab.tools" as the group ID after the project has been split in multiple artifacts. That's why I changed it to org.openhab.tools.sat.
The Maven plugin itself is now called "sat-plugin" on the file system, that's why I adapted the artifactId accordingly.
If you agree that this makes sense, please help adapting the docs (ideally by pushing commits to this branch directly).

**Comment by svilenvul** [comment]
@kaikreuzer, I am ok with the changes.

I looked at the documentation, only a few changes are required.
I will try to make them today or tomorrow.

**Comment by kaikreuzer** [comment]
Cool, thanks!

**Comment by svilenvul** [comment]
@kaikreuzer, do you have anything to add in this PR before merging it ?

**Comment by kaikreuzer** [comment]
@svilenvul No, nothing more to add - thanks for the docs update!

**Pull request merged**
