### PR TITLE
[checkstyle] ESH-INF has been moved to src/main/resources

### PR DESCRIPTION
**Pull request by Hilbrand**
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>

### CODE REVIEW

**Comment by wborn** [comment]
Did you also check if we need PRs for fixing isuses in other repos besides openhab2-addons @Hilbrand ?

**Comment by Hilbrand** [comment]
No didn't check. That will be zigbee and zwave I guess?

**Comment by wborn** [comment]
Yes and openhab-core. :-)

**Comment by Hilbrand** [comment]
- [x] openab-webui [pr 124](https://github.com/openhab/openhab-webui/pull/124)
- [x] zigbee [pr 503](https://github.com/openhab/org.openhab.binding.zigbee/pull/503)
- [x] zwave [pr 1241](https://github.com/openhab/org.openhab.binding.zwave/pull/1241)
- [x] core No schema files present (binding all moved)

**Comment by wborn** [comment]
Many thanks @Hilbrand ! :+1:

**Pull request merged**
