### PR TITLE
Corrected incorrect import which caused compilation errors...

### PR DESCRIPTION
**Pull request by martinvw**
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

### CODE REVIEW

**Comment by svilenvul** [comment]
Thanks !

@kaikreuzer , you may be interested in this change.

**Comment by kaikreuzer** [comment]
> @kaikreuzer , you may be interested in this change.

Why, do you think it could be related to our build problems?

**Comment by martinvw** [comment]
It was really recent so I don't expect it to

**Comment by svilenvul** [comment]
I forgot that this was not part of the 0.0.4 release.

**Pull request merged**
