### PR TITLE
HTML report styling improvements

### PR DESCRIPTION
**Pull request by wborn**
* Use Main UI inspired styles
* Add support for dark mode :sunglasses: 
* Add a bit more margins and padding
* Use nicer timestamps

### CODE REVIEW

**Comment by wborn** [comment]
Can you create a new SAT release after merging this last PR @kaikreuzer?

**Review by martinvw — APPROVED** [review]

**Comment by martinvw** [comment]
@kaikreuzer I can merge but will you make the release?

**Review by kaikreuzer — APPROVED** [review]
I'll try to do a new release within the next days! 👍

**Comment by kaikreuzer** [comment]
@wborn Done: https://github.com/openhab/static-code-analysis/releases/tag/0.12.0

**Comment by wborn** [comment]
Many thanks, also for closing all the stale issues/PRs!
I'll create some PRs so we can use the new release.

**Pull request merged**
