### PR TITLE
Feature/log warnings and infos

### PR DESCRIPTION
**Pull request by martinvw**
I really like maven to report warnings if things are (a little bit) wrong, this was something I always missed for the static-code-analysis. 

```
[INFO] --- static-code-analysis:0.3.0-SNAPSHOT:report (default) @ org.openhab.binding.hdpowerview ---
[INFO] Individual report appended to summary report.
[WARNING] Code Analysis Tool has found: 
 1 error(s)! 
 2 warning(s) 
 8 info(s)
[ERROR] .binding.hdpowerview/build.properties:[0]
about.html file must be added to the bin.includes property
[WARNING] .binding.hdpowerview/build.properties:[0] 
about.html file must be added to the bin.includes property
[WARNING] .binding.hdpowerview/META-INF/MANIFEST.MF:[12]
The version of the package javax.ws.rs.client should not be specified
[WARNING] .binding.hdpowerview/META-INF/MANIFEST.MF:[13]
The version of the package javax.ws.rs.core should not be specified
[INFO] Detailed report can be found at: file:////Users/martinvw/IdeaProjects/openhab2-addons/addons/binding/org.openhab.binding.hdpowerview/target/code-analysis/report.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.650 s
[INFO] Finished at: 2017-08-20T12:06:26+02:00
[INFO] Final Memory: 64M/666M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0-SNAPSHOT:report (default) on project org.openhab.binding.hdpowerview: 
[ERROR] Code Analysis Tool has found 1 error(s)! 
[ERROR] Please fix the errors and rerun the build. 
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### CODE REVIEW

**Comment by martinvw** [comment]
@svilenvul can you review mine :-)

**Comment by svilenvul** [comment]
Looks great :) and thanks for improving the tests.

I will merge it once the conflicts are resolved.

**Comment by martinvw** [comment]
I already did that some hours ago, does it still show conflicts with you?

**Comment by svilenvul** [comment]
Yes, I have merged some things after that :-) :

>This branch cannot be rebased due to conflicts. Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by martinvw** [comment]
I merged it online but that seemed to give you other errors I just rebased it locally now, that should fix it.

**Comment by svilenvul** [comment]
Thanks !

**Pull request merged**
