### PR TITLE
A check for author tag is implemented. Some tests for it are added.

### PR DESCRIPTION
**Pull request by m-memova**
Signed-off-by: Mihaela Memova <mihaela.memova@musala.com>

### CODE REVIEW

**Comment by svilenvul** [comment]
Great, thanks, please update the README.MD file with the priority of the check.

**Comment by m-memova** [comment]
@kaikreuzer , are you OK with this check failing the build or should I change its priority to "warning"?

**Comment by kaikreuzer** [comment]
Failing the build is fine, thanks!

**Comment by m-memova** [comment]
Done! :)

**Comment by m-memova** [comment]
So, I tried this check in the addons2 repository. And it turned out that more than 100 classes have no author tags. That means that when this PR is merged, the build will fail for every new PR. So I searched through all the bindings and I made a list of potentials authors. I think it would be nice to make an issue [here](https://github.com/openhab/openhab2-addons/issues). If the authors add their tags before merging this PR, the build will be successful. @kaikreuzer, @svilenvul , what do you think?

**Comment by kaikreuzer** [comment]
I fear that it will take forever to ask the individual authors to add that.
Question: Is it easily possible to deactivate certain rules on certain bundles? Then we could add an "ignore" to the pom.xmls of the concerned bundles and still would have the check in place for any new contribution.

**Comment by m-memova** [comment]
I can add all the files-with-no-author tag in the  suppressions.xml file. But I am not sure that would be a better decision. Besides, there are several things to consider : 
- 71 of those files are from org.openhab.ui.cometvisu (judging by the rest of the files there, we can be pretty sure that the author is Tobias Bräutigam)
- many of the files with no author tag are from internal packages (according to the ESH guidelines every file must have an author tag but still...)

**Comment by kaikreuzer** [comment]
> 71 of those files are from org.openhab.ui.cometvisu (judging by the rest of the files there, we can be pretty sure that the author is Tobias Bräutigam)

I just quickly scanned through this bundle and only saw a single class where the tag was missing. Do you have details?

> many of the files with no author tag are from internal packages (according to the ESH guidelines every file must have an author tag but still...)

There might be SOME exceptions, like e.g. generated code (e.g. JAXB beans) or third-party code that has been included in the repo - both are valid exceptions to the rule, so for those cases it would be nice if there is a chance to configure the bundle in a way that this check is suppressed.

**Comment by martinvw** [comment]
@kaikreuzer we can of course track back the authors by doing some git blames, or is that not sufficient.

**Comment by kaikreuzer** [comment]
@martinvw That won't help for the two exceptional cases that I mentioned (generated & 3rd party code).

**Comment by m-memova** [comment]
@kaikreuzer , you are right, 70 of the files with no author tag in org.openhab.ui.cometvisu are generated by the JavaTM Architecture. I will think about how we can handle those exceptions of the rule.

**Comment by martinvw** [comment]
In most projects I worked on professionally we put the generated code in the target directory and let maven generate it on each build, we could try whether that is a possible option here too. It would solve this problem and make sure the generated code is not accidentally altered 

@kaikreuzer what would you think about this?

**Comment by svilenvul** [comment]
I think for now we can just add them to the suppression filter. (since most of the files are in a single bundle).
@m-memova, what do you think about this ?

**Comment by kaikreuzer** [comment]
> we put the generated code in the target directory and let maven generate it on each build

I only do this for code that we do not compile against ourselves - the rest is checked in, because otherwise you will have hundreds of compilation errors after doing the IDE setup.
This is the beauty of the OH2 IDE setup over the ESH IDE: It does not require any additional code generation steps and thus is much simpler to get started with.

**Comment by martinvw** [comment]
> This is the beauty of the OH2 IDE setup over the ESH IDE: It does not require any additional code generation steps and thus is much simpler to get started with.

Maybe that is more something to debate over beer, but I would not consider it beauty that you lose track of the difference between generated code and potentially customized (generated) code :-)

**Comment by kaikreuzer** [comment]
Yes, I go for the beer 🍻

**Comment by svilenvul** [comment]
I am sure that all of us would like to see this check merged :-), so I will start resolving some of the errors. I still have some questions :
- there are some bundles that contain one ore two classes that miss the author tag. Is it OK to add the authors using the information from git blame?
- there are some auto generated classes. Is it possible to move them to ``src/gen/java`` source folder and ignore them directly in the check, or they will be added in the exclude filter ?
- there are some multi line comments that should be changed to javadoc;

**Comment by martinvw** [comment]
> there are some auto generated classes. Is it possible to move them to src/gen/java source folder and ignore them directly in the check, or they will be added in the exclude filter ?

I think that that is great solution

**Comment by svilenvul** [comment]
The cleanup is done :).

Are we ready to merge this check as well ?

**Pull request merged**
