### PR TITLE
Add check to generate a warning if the exception is not added as a last parameter

### LINKED ISSUE #221: [Logging] add exception as last parameter
Another possible logging check:
- Where ever unchecked exceptions are caught and logged, the exception should be added as a last parameter to the logging
- For checked exceptions, this is normally not recommended, unless it can be considered an error situation and the stacktrace would hold additional important information for the analysis.

### PR DESCRIPTION
**Pull request by ghost**
Add new check to generate a warning if the exception is not added as a last parameter to the logging for caught and logged unchecked exceptions.
Fixed #221

### CODE REVIEW

**Comment by svilenvul** [comment]
@martinvw, please take a look when you have time for that.

**Comment by dstivanov** [comment]
@tanyatanyatanya Can you please adapt the PR according to the changes in #287 ?

**Comment by tanyatanyatanya** [comment]
@dstivanov Done.

**Comment by Hilbrand** [comment]
There is a pmd check that kind of checks for this too: [UseCorrectExceptionLogging](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#usecorrectexceptionlogging). Was that considered or doesn't cover the use case implemented in this check?

**Comment by kaikreuzer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
