### PR TITLE
Ignored test correction

### PR DESCRIPTION
**Pull request by doandzhi**
Signed-off-by: Erdoan Hadzhiyusein <3rdoan@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
The problem is in the capitals of the test file name README.**MD**' instead of 'README.md'

**Comment by martinvw** [comment]
Linux has that problem MacOs and Windows are case insensitive on their file systems.

**Comment by doandzhi** [comment]
Thanks a lot! 👍

**Comment by svilenvul** [comment]
Thanks all.

**Pull request merged**
