### PR TITLE
create a check to warn if there are trailing Whitespaces

### LINKED ISSUE #272: Trailing whitespaces
WDYT about a test that complains about trailing whitespace?
An inclusion and exclusion list (regular expression for the path pattern) could make sense.

### PR DESCRIPTION
**Pull request by lpapazow**
This PR fixes #272.

Currently, it's not possible to create tests because of #294.

Once #296 is merged tests could be created.

Signed-off-by: Lyubomir V. Papazov <lpapazow@gmail.com>

### CODE REVIEW

**Comment by svilenvul** [comment]
The update is merged, so you can continue with the tests.

**Comment by lpapazow** [comment]
Tests are now included.

**Comment by martinvw** [comment]
Is this check really worth it, I don't know what the added time on ESH / OH is for this check, but I personally care much more about build time then whitespace on the end of my lines, wdyt?

**Comment by martinvw** [comment]
@maggu2810, what about my remark above, checking every single line of every single file with a regex does not sound like a free check for me?

**Comment by maggu2810** [comment]
Hm, personally I differ between
* I would like to execute the checks and grant that the sources fits our requirements
* I would like to get new build artifacts (and don't execute the tests)

I would assume that most of the checks that operate on the source code files and not on the bytecode read and inspect every line of the file.
So, if you really want to improve the situation, checks should be combined to not read every file again and again...
But I don't think that "check for whitespaces" consumes more time as every other check that inspect the source code.

**Comment by lpapazow** [comment]
With the addition of #316 it will be possible to only perform analysis on the changed bundles. Maybe with this option the check would be worth the time?
@martinvw wdyt?

**Comment by kaikreuzer** [comment]
Closed as suggested in https://github.com/openhab/static-code-analysis/issues/272#issuecomment-619452218

**Pull request closed without merging**
