### PR TITLE
Upgrade maven-pmd-plugin to fix incremental analysis warnings

### LINKED ISSUE #330: Incremental Analysis Warnings
When I use SAT 0.6.0-SNAPSHOT the build contains a lot of warnings about using "Incremental Analysis" to make analysis faster. Can we solve the warnings by using incremental analysis which also makes the analysis faster?

Example:

```
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis
```

It is really spamming the output because it shows many of these lines again and again after each other.

### PR DESCRIPTION
**Pull request by wborn**
Upgrades the maven-pmd-plugin to 3.11.0 which has a fix for [MPMD-257](https://issues.apache.org/jira/browse/MPMD-257).

Fixes #330

### CODE REVIEW

**Comment by martinvw** [comment]
If i remember correctly there are more places: 
https://github.com/openhab/static-code-analysis/pull/331/files

**Comment by wborn** [comment]
Like Spotbugs there's a PMD and a PMD Maven plugin version. This PR only updates the PMD Maven plugin version. As far as I can see all places have been updated @martinvw . :-)

**Comment by kaikreuzer** [comment]
@martinvw You should also have the rights to merge!

**Comment by martinvw** [comment]
Yes, but note that merge commits are still selected you default

**Comment by kaikreuzer** [comment]
Good point, I have just deactivated it now!

**Pull request merged**
